auth/urls.py
# -*- coding: utf-8 -*-
"""auth app URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('auth/', include('auth.urls'))
"""
from django.conf.urls import url

from . import views

app_name = 'auth'
urlpatterns = [
    url(r'^register$', views.Register.as_view(), name='register'),
    url(r'^login_ajax_check$', views.login_ajax_check, name='login_ajax_check'),
    url(r'^sign_up_ajax_check$', views.sign_up_ajax_check, name='sign_up_ajax_check'),
    url(r'^login$', views.AuthLogin.as_view(), name='login'),
    url(r'^logout$', views.AuthLogout.as_view(), name='logout'),
    url(r'^verify_code/([0-9]+)$', views.verify_code, name='verify_code'),
]

blog/urls.py
# -*- coding: utf-8 -*-
"""blog app URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import url

from . import views
from django.views.decorators.cache import cache_page

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<post_id>[0-9]+)/$', views.Detail.as_view(), name='detail'),
    url(r'view_post/(?P<post_id>[0-9]+)/$', views.PostDetailView.as_view(), name='detailbyid'),
    # 测试一下使用detail view
    url(r'^get_time/$', views.get_time, name='get_time'),
    url(r'^submit_comment/$', views.submit_comment, name='submit_commit'),
    url(r'^search/$', views.Search.as_view(), name='search'),
    url(r'^404$', views.page_not_found, name='404'),
    url(r'^500$', views.page_error),
    url(r'^test$', views.test, name='test'),
]

django_blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'

# ... the rest of your URLconf goes here ...

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('auth.urls')),
    url(r'^web-spider/', include('webSpider.urls')),
    url(r'', include('blog.urls')),
]
urlpatterns += staticfiles_urlpatterns()

blog/models.py
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
   File Name：     blog/models.py
   Description :
   Author :       JWang
   date：          2018/10/24
-------------------------------------------------
   Change Activity:
                   2018/10/24:
-------------------------------------------------
"""
__author__ = 'JWang'

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
# 如果想继承user
#             new_user = user_form.save(commit=False)
#             new_user.set_password(user_form.cleaned_data['password'])
#             new_user.save()
#             profile = Profile.objects.create(user=new_user)
"""
class Profile(models.Model):

    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    image = models.ImageField(upload_to='static/image/%Y/%m', default='static/image/default.jpg', max_length=200,
                              blank=True, null=True, verbose_name='用户头像')
    created_dt = models.DateTimeField(auto_now_add=True, db_index=True)
    date_of_birth = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return self.user.username
"""


class Tag(models.Model):
    """
    文章标签
    tag of posts
    """
    tag_name = models.CharField(u'标签名', max_length=100)

    def __str__(self):
        return self.tag_name


class Category(models.Model):
    """
    文章类型
    tag of posts
    """
    category_name = models.CharField(u'文章类型', max_length=100)

    def __str__(self):
        return self.category_name


class Post(models.Model):
    # 内容相关
    title = models.CharField(max_length=200)  # 博客标题
    body = models.TextField(blank=True, null=True)  # 文章正文
    digest = models.TextField(blank=True, null=True)  # 文章摘要
    picture = models.CharField(max_length=200)  # 标题图片地址
    # 时间相关
    created_time = models.DateTimeField(auto_now_add=True)  # 文章的创建时间
    modified_time = models.DateTimeField()  # 文章最后修改时间
    # 其他人阅读评论
    view_num = models.BigIntegerField(default=0)  # 阅读数
    comment_num = models.BigIntegerField(default=0)  # 评论数
    # 外键
    author = models.ForeignKey(User, verbose_name=u'作者', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', verbose_name=u'文章类型', on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, blank=True)  # 标签

    def __str__(self):
        return "文章: " + self.title + "\n作者：" + self.author.__str__()

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'post_id': self.id})

    def viewed(self):
        self.view_num += 1
        self.save(update_fields=['view_num'])

class Comment(models.Model):
    # 内容相关
    body = models.CharField(verbose_name='内容', max_length=300)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    # 外键相关
    post = models.ForeignKey(Post, verbose_name='博客', on_delete=models.CASCADE)
    parent = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论', on_delete=models.SET_NULL)
    user = models.ForeignKey(User, verbose_name=u'作者', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '博客评论'
        verbose_name_plural = verbose_name
        ordering = ['-create_time']

    def __str__(self):
        return self.body[:10]

blog/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.core.validators import RegexValidator


# 注册
class RegisterForm(forms.Form):
    error_msg = {
        'username': {'required': '用户名不能为空', 'max_length': '最大20', 'min_length': '用户名长度至少6'},
        'password': {'required': '用户名密码不能为空', 'max_length': '最大20', 'min_length': '密码长度至少6'},
    }
    username = forms.CharField(label='用户名', min_length=6, max_length=20, required=True,
                               error_messages=error_msg['username'])
    password = forms.CharField(label='密码', min_length=6, max_length=20, required=True,
                               validators=[
                                   RegexValidator(r'((?=.*\d))^.{6,20}$', '密码必须包含数字'),
                                   RegexValidator(r'((?=.*[a-zA-Z]))^.{6,20}$', '密码必须包含字母'),
                                   RegexValidator(r'((?=.*[^a-zA-Z0-9]))^.{6,20}$', '密码必须包含特殊字符'),
                                   RegexValidator(r'^.(\S){6,20}$', '密码不能包含空白字符'),
                               ],  # 用于对密码的正则验证
                               error_messages=error_msg['password'], widget=forms.PasswordInput)
    password_again = forms.CharField(label='确认密码', min_length=6, max_length=20, required=True,
                                     error_messages={'required': '密码不能为空!'}, widget=forms.PasswordInput)

    email = forms.EmailField(
        label='邮箱',
        required=True,
        min_length=6,
        max_length=30,
        error_messages={'required': '邮箱不能为空',
                        'invalid': '请输入正确的邮箱格式'},
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        users = User.objects.filter(username=username)
        print(username)
        if users:
            raise forms.ValidationError("用户名已经存在")
        return username

    def clean_email(self):
        # 对email的扩展验证，查找用户是否已经存在
        email = self.cleaned_data.get('email')
        email_count = User.objects.filter(email=email).count()  # 从数据库中查找是否用户已经存在
        if email_count:
            raise forms.ValidationError('该邮箱已经注册！')
        return email

    def clean__password_again(self):  # 查看两次密码是否一致
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password_again')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError('两次密码不匹配！')


# 登录
class LoginForm(forms.Form):
    error_msg = {
        'username': {'required': '用户名不能为空', 'max_length': '最大20', 'min_length': '至少6'},
        'password': {'required': '用户名密码不能为空', 'max_length': '最大20', 'min_length': '至少6'},
    }
    username = forms.CharField(label='用户名', min_length=6, max_length=20, required=True,
                               error_messages=error_msg['username'])
    password = forms.CharField(label='密码', min_length=6, max_length=20, required=True,
                               error_messages=error_msg['password'], widget=forms.PasswordInput)

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect, render_to_response
from .models import Post, Comment
from django.views import View
from django.urls import reverse
from django.views.decorators.cache import cache_page
import time
from django.views.generic.detail import DetailView
from django.core.cache import cache
from django.utils.safestring import mark_safe
import markdown


# Create your views here.
class Detail(View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        post.view_num = post.view_num + 1
        post.save()
        comment_list = Comment.objects.filter(post=post)
        post.body = markdown.markdown(post.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        return render(request, 'blog/detail.html', context={'post': post, 'comment_list': comment_list})


# 另一种方法，使用detail view
class PostDetailView(DetailView):
    template_name = 'blog/detail.html'
    model = Post
    pk_url_kwarg = 'post_id'
    context_object_name = "post"

    def get_object(self, queryset=None):
        obj = super(PostDetailView, self).get_object()
        obj.viewed()
        self.object = obj
        return obj

    def get_context_data(self, **kwargs):
        postid = int(self.kwargs[self.pk_url_kwarg])
        comment_list = Comment.objects.filter(post_id=postid)
        kwargs['comment_list'] = comment_list

        return super(PostDetailView, self).get_context_data(**kwargs)


def aside():
    post_list_newest = Post.objects.all().order_by('-created_time')
    return post_list_newest[0:3]


def pagenation(request, current_url, post_list_length=6, model_name=Post, get_condition=None):
    if request.method == 'GET':
        # post per page
        post_per_page = int(request.COOKIES.get('post_per_page', 3))
        print('post_per_page is ', post_per_page)
        if post_per_page not in [3, 10, 50, 100]:
            post_per_page = 3
        print('post_per_page is ', post_per_page)
        # url list
        page_index_list = []
        count, remain = divmod(post_list_length, post_per_page)
        max_page_num = count + 1 if remain > 0 else count

        # page_num
        page_num = int(request.GET.get('p', 1))
        page_num = page_num if page_num > 1 else 1
        page_num = page_num if page_num <= max_page_num else max_page_num

        # post_list
        post_start = (page_num - 1) * post_per_page
        post_end = page_num * post_per_page
        if get_condition:
            post_list = model_name.objects.filter(get_condition)[post_start, post_end]
        else:
            post_list = model_name.objects.all().order_by('-created_time')
            post_list = post_list[post_start: post_end]
        # page_index_list，也就是所有页的index
        start_page_num = page_num - 4 if page_num >= 4 else 0
        end_page_num = page_num + 3 if page_num <= (max_page_num - 3) else max_page_num

        for page_i in range(start_page_num, end_page_num):
            temp = "<li><a href='%s?p=%s'>%s</a></li>" % (current_url, page_i + 1, page_i + 1)
            if page_i + 1 == page_num:
                temp = "<li class='active'><a href='%s?p=%s'>%s<span class='sr-only'>(current)</span></a></li>" % (
                    current_url, page_i + 1, page_i + 1)
            page_index_list.append(temp)

        # url list--> str --> mark_safe
        page_index = ' '.join(page_index_list)
        page_index = mark_safe(page_index)

        # 上一页和下一页的class
        last_page_class = ''
        next_page_class = ''

        # 上一页和下一页的index
        last_page_href = '%s?p=%s' % (current_url, page_num - 1)
        next_page_href = '%s?p=%s' % (current_url, page_num + 1)
        if page_num == 1:
            last_page_href = '%s?p=%s' % (current_url, 1)
            last_page_class = 'disabled'
        if page_num == max_page_num:
            next_page_href = '%s?p=%s' % (current_url, page_num)
            next_page_class = 'disabled'

        # return
        return page_index, post_list, last_page_href, next_page_href, last_page_class, next_page_class, max_page_num


def index(request):
    post_list_newest = aside()
    current_url = reverse('blog:index')
    post_list_length = len(Post.objects.all())

    page_index, post_list, last_page_href, next_page_href, last_page_class, next_page_class, max_page_num = \
        pagenation(request, current_url, post_list_length)
    return render(request, 'blog/index.html', context={
        'post_list': post_list,
        'page_index': page_index,
        'title': '我的博客首页',
        'post_list_newest': post_list_newest,
        'last_page_href': last_page_href,
        'next_page_href': next_page_href, 'last_page_class': last_page_class,
        'next_page_class': next_page_class, 'max_page_num': max_page_num
    })


def submit_comment(request):
    if request.method == 'POST':
        temp_user = request.user
        temp_body = request.POST.get('comment_body')
        post_id = request.POST.get('post_id')
        if temp_body and 2 < len(temp_body) < 550:
            print(temp_user, temp_body, post_id)
            if temp_user and post_id:
                new_comment = Comment.objects.create(body=temp_body, user=temp_user, post_id=post_id)
                new_comment.save()
                post = Post.objects.filter(id=post_id)[0]
                post.comment_num = post.comment_num + 1
                post.save()
                return redirect(reverse('blog:detail', kwargs={'post_id': post_id}))
        if not temp_body:
            print('not temp')
        else:
            print(len(temp_body))
        return HttpResponse('wrong request')


def recommend():
    post_list = Post.objects.all().order_by('view_num')
    return post_list[0:3]


@cache_page(48 * 3600)
def page_not_found(request):
    post_list = recommend()
    return render_to_response('errors/404.html', context={'post_list': post_list})


@cache_page(48 * 3600)
def page_error(request):
    post_list = recommend()
    return render_to_response('errors/500.html', context={'post_list': post_list})


class Search(View):
    def post(self, request):
        print('post', request.POST)
        title = request.POST.get('title', 'django')
        error_msg = ''
        post_list = None

        if not title:
            error_msg = '请输入关键词'
        else:
            post_list = Post.objects.filter(title__icontains=title)

        return render(request, 'blog/index.html', {'error_msg': error_msg,
                                                   'post_list': post_list})


def view_post(post_id):
    post = get_object_or_404(Post, id=post_id)
    post.view_num = post.view_num + 1
    post.save()
    num_list = [post.view_num, post.comment_num]
    return num_list


def get_time():
    return time.time()


def test(request):
    return render(request, 'test.html')

templates/blog/blog_index.html
{% load staticfiles %}
<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
<div style="margin-top: 17px;">
    <style type="text/css">
        * {
            margin: 0;
            padding: 0;
            list-style-type: none;
        }

        a, img {
            border: 0;
        }≠

        .mr-19 {
            margin-right: 19px;
        }
    </style>
    <!-- 轮播 -->
    <div class="flexslider" style="height: 100%; z-index: 0;">
        <ul class="slides">
            <li id="slider-1"
                style="background:url({% static 'img/bg_img/swiper/img2.jpg' %}) 50% 0 no-repeat;"></li>
            <li id="slider-2"
                style="background:url({% static 'img/bg_img/swiper/img3.jpg' %}) 50% 0 no-repeat;"></li>
            <li id="slider-3"
                style="background:url({% static 'img/bg_img/swiper/img1.jpg' %}) 50% 0 no-repeat;"></li>
            <li id="slider-4"
                style="background:url({% static 'img/bg_img/swiper/img4.jpg' %}) 50% 0 no-repeat;"></li>
            <li id="slider-5"
                style="background:url({% static 'img/bg_img/swiper/img5.jpg' %}) 50% 0 no-repeat;"></li>
        </ul>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery.flexslider-min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.flexslider').flexslider({
                directionNav: true,
                pauseOnAction: false
            });
        });
    </script>
    <!-- 轮播上跟随鼠标滑动的文字-->
    <div id="slider-hint" style="z-index: 10"></div>
    <script src="{% static "js/custom-index.js" %}" type="text/javascript"></script>
    <!-- end  轮播上跟随鼠标滑动的文字-->
    <!-- 结束轮播 -->
    <!-- post and 分页-->
    <div>
        <!-- post -->
        {% for post in post_list %}
            <div style="margin: 20px 0;">
                <div class="post post-{{ post.pk }}">
                    <h4 class="post-title">
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </h4>
                    <div class="post-content">
                        <p>{{ post.digest }}</p>
                    </div>
                    <div class="post-meta" style="display: flex; justify-content: space-between; padding-bottom: 10px">
                        <div>
                            <span class="post-category">{{ post.category.name }}</span>
                            <time class="post-date"
                                  datetime="{{ post.created_time }}">{{ post.created_time|date:"Y-m-d" }}</time>
                            <span class="post-author">{{ post.author }}</span>
                            <span class="comments-link">{% if post.comment_num > 0 %}{{ post.comment_num }} {% else %}
                                0{% endif %} 评论</span>
                            <span class="views-count">{{ post.view_num }} 阅读</span>
                        </div>
                        <div class="read-more">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="no-post">暂时还没有发布的文章！</div>
        {% endfor %}
        <!-- end post -->
        <!-- post 分页 -->
        <nav aria-label="Page navigation">
            <div class="total-pagination">
                <div style="line-height: 1.42857143; margin: 20px 0; padding: 6px 12px;">
                    <select id='post_per_page' onchange="post_per_page_change()" name="每页数量">
                        <option value="3">3</option>
                        <option value="10">10</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                    <span>条每页</span>
                </div>
                <div>
                    <ul class="pagination">
                        <li class="{{ last_page_class }}">
                            <a href="{{ last_page_href }}" aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                        </li>
                        {{ page_index }}
                        <li class="{{ next_page_class }} mr-19">
                            <a href="{{ next_page_href }}" aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                        </li>
                        <li class="pagination-phone-block mr-19">
                            共{{ max_page_num }}页
                        </li>
                        <li class="pagination-phone-block mr-19">
                            到第<input id="choose_page" style="padding: 5px; margin: 0 3px;
    border: 1px solid #ddd" size="3" maxlength="3"/>页
                        </li>
                        <li class="pagination-phone-block mr-19">
                            <button onclick="go_page()">前往</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- end 分页 -->
    </div>
    <!-- end post 和 分页 -->
    <!-- 分页的js -->
    <script>
        function onload_post_per_page() {
            const post_per_page = $.cookie('post_per_page');
            if (post_per_page) {
                $('#post_per_page').val(post_per_page);
            }
        };

        function onload_pageination() {
            let blogWide = document.body.clientWidth;
            console.log('11111');
            if (blogWide < 750) {
                let blog_index = document.getElementsByClassName('pagination-phone-block');
                for (let i = 0; i < blog_index.length; i++) {
                    blog_index[i].className += ' hidden';
                    console.log(i);
                }
                console.log(blog_index[0].className);
            }
            ;
        };

        function onload_blogindex() {
            onload_pageination();
            onload_post_per_page();
        };

        window.onload = onload_blogindex();

        function post_per_page_change() {
            const val = $('#post_per_page').val();
            console.log(val);
            $.cookie("post_per_page", val, {expires: 1, path: "{% url 'blog:index' %}"});
            location.reload();
        };

        function go_page() {
            if ($('#choose_page').val() == "") {
                alert("请输入页数");
                return false;
            }
            const p = document.getElementById('choose_page').value;
            const url = "{% url 'blog:index' %}" + "?p=" + p;
            window.open(url, '_self');
        };
    </script>
    <!-- end 分页 js-->
</div>

templates/blog/comment.html
{% load staticfiles %}
<div style="border-bottom: 1px solid #777; padding: 15px 25px; margin: 15px 0px; background: rgba(255, 255, 255, 0.5);">
    {% if user.is_authenticated %}
        <div>
            <label><h3>发表评论：</h3></label>
            <form class="form-horizontal" role="form" action="{% url 'blog:submit_commit' %}"
                  method="post">{% csrf_token %}
                <div class="form-group" style="display: none">
                    {% if post %}
                        <input name="post_id" value="{{ post.id }}">
                    {% endif %}
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <i class="fa fa-pencil-square-o"></i>
                        <textarea name="comment_body" maxlength="500" minlength="3" rows="5"
                                  class="form-control"
                                  id="message"
                                  placeholder="最小字数3 最大500" style="width: 100%;"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="submit" value="发表评论" class="btn btn-warning pull-right">
                    </div>
                </div>
            </form>
        </div>
    {% else %}
        <div class="text-center">
            <span style="font-size: 18px; font-weight: 400;">想对作者说些什么</span>
            <a href="{% url 'auth:login' %}">
                <button class="btn btn-danger">我来说一句</button>
            </a>
        </div>
    {% endif %}
</div>

templates/blog/detail.html
{% extends 'base.html' %}

{% block title %} {{ post.title }} {% endblock %}

{% block body %}
    <div id="post-detail">
        {% if post %}
            <!-- 文章内容 -->
            <article class="post post-{{ post.pk }}" style="padding: 15px 25px;" >
                <h1 class="post-title">
                    {{ post.title }}
                </h1>
                <div class="post-meta" style="text-align: right">
                    <span class="post-category">{{ post.category.name }}</span>
                    <span class="post-date"><time class="entry-date"
                                                  datetime="{{ post.created_time }}">{{ post.created_time|date:"Y-m-d H:i:s" }}</time></span>
                    <span class="post-author">{{ post.author }}</span>
                    <span class="comments-link" id="comment-num">{{ post.comment_num }}评论</span>
                    <span class="views-count" id="view-num">{{ post.view_num }}阅读</span>
                </div>
                <div class="post-content" style="padding-bottom: 10px;">
                    <span>
                        {{ post.body|safe }}
                    </span>
                </div>
            </article>
            <!-- end of 文章内容-->

            <!-- 发表评论 -->
            {% include 'blog/comment.html' %}
            <!-- 结束发表评论 -->

            <section class="comment-area" id="comment-area">
                <!-- 显示评论 -->
                <div class="comment-list-panel">
                    {% if comment_list %}
                        <h3>评论列表，共 <span>{{ post.comment_num }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                                <li class="comment-item">
                                    <span class="nickname">{{ comment.user }}</span>
                                    <time class="submit-date"
                                          datetime="2012-11-09T23:15:57+00:00">{{ comment.create_time|date:"Y-m-d H:i:s" }}</time>
                                    <div class="text">
                                        {{ comment.body }}
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                </div>
                <!-- end of 显示评论-->
            </section>
            <!-- end of 评论-->
        {% endif %}
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        function onload_detail() {
            //判断是否宽屏
            let winWide = document.body.clientWidth;
            console.log(winWide);
            if (winWide >= 1000) {
                $('#post-detail').addClass('col-md-8');
                $('#post-detail').addClass('container-magin');
                $('.post').addClass('container-magin');
            };
        };
        window.onload = onload_detail();
    </script>
    <script>
    $(document).ready(function ()  {
        for (let i = 1; i < 5; i++) {
            let base_nav_bottom_li_id = "base-nav-bottom-li-" + i;
            $('#' + base_nav_bottom_li_id).removeClass('active');// remove class
        }
        $("#base-nav-bottom-li-1").addClass('active');
    });
    </script>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block body %}
    <div id="base-index">
        <!-- 问候 nav正下边-->
        <div id="inf-d" style="padding-left: 10px;">
            <div id="inf-b" style="padding: 5px 0; height: 12px;">
                Hi,
                <script type="text/javascript">
                    today = new Date();
                    var day;
                    var date;
                    var hello;
                    hour = new Date().getHours();
                    if (hour < 6) {
                        hello = ' 凌晨好！ 别熬夜了哦   ';
                    } else if (hour < 9) {
                        hello = ' 早上好！';
                    } else if (hour < 12) {
                        hello = ' 上午好！';
                    } else if (hour < 14) {
                        hello = ' 中午好！ ';
                    } else if (hour < 17) {
                        hello = ' 下午好！ ';
                    } else if (hour < 19) {
                        hello = ' 傍晚好！';
                    } else if (hour < 22) {
                        hello = ' 晚上好！ ';
                    } else {
                        hello = '夜深了！早点睡哦     ';
                    }

                    function GetCookie(sName) {
                        var arr = document.cookie.match(new RegExp("(^| )" + sName + "=([^;]*)(;|$)"));
                        if (arr != null) {
                            return unescape(arr[2])
                        }
                        ;
                        return null;
                    }

                    var Guest_Name = decodeURIComponent(GetCookie('author'));
                    var webUrl = webUrl;
                    if (Guest_Name != "null" && Guest_Name != "") {
                        hello = Guest_Name + ' , ' + hello + ' 欢迎回来。';
                    }
                    document.write(' ' + hello);
                </script>
                今天是：
                <span id="localtime">
                    <script type="text/javascript">
                    today = new Date();
                    var tdate, tday, x, year;
                    var x = new Array("星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六");
                    var MSIE = navigator.userAgent.indexOf("MSIE");
                    if (MSIE != -1) {
                        year = (today.getFullYear());
                    } else {
                        year = (today.getYear() + 1900);
                    }
                    tdate = year + "年" + (today.getMonth() + 1) + "月" + today.getDate() + "日" + " " + x[today.getDay()];
                    document.write(tdate);
                    </script>
                </span><!---->
            </div>
        </div>
        <!-- end 问候-->
        {% if error_msg %}{{ error_msg }}{% endif %}
        {% include 'blog/blog_index.html' %}
    </div>
{% endblock %}

{% block js %}
    <script>
    $(document).ready(function ()  {
        for (let i = 1; i < 5; i++) {
            let base_nav_bottom_li_id = "base-nav-bottom-li-" + i;
            $('#' + base_nav_bottom_li_id).removeClass('active');// remove class
        }
        $("#base-nav-bottom-li-1").addClass('active');
    });
    </script>
{% endblock %}