auth/urls.py
# -*- coding: utf-8 -*-
"""auth app URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('auth/', include('auth.urls'))
"""
from django.conf.urls import url

from . import views

app_name = 'auth'
urlpatterns = [
    url(r'^register$', views.Register.as_view(), name='register'),
    url(r'^login_ajax_check$', views.login_ajax_check, name='login_ajax_check'),
    url(r'^sign_up_ajax_check$', views.sign_up_ajax_check, name='sign_up_ajax_check'),
    url(r'^login$', views.AuthLogin.as_view(), name='login'),
    url(r'^logout$', views.AuthLogout.as_view(), name='logout'),
    url(r'^verify_code/([0-9]+)$', views.verify_code, name='verify_code'),
]

blog/urls.py
# -*- coding: utf-8 -*-
"""blog app URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import url

from . import views
from django.views.decorators.cache import cache_page

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<post_id>[0-9]+)/$', views.Detail.as_view(), name='detail'),
    url(r'view_post/(?P<post_id>[0-9]+)/$', views.PostDetailView.as_view(), name='detailbyid'),
    # 测试一下使用detail view
    url(r'^get_time/$', views.get_time, name='get_time'),
    url(r'^submit_comment/$', views.submit_comment, name='submit_commit'),
    url(r'^search/$', views.Search.as_view(), name='search'),
    url(r'^404$', views.page_not_found, name='404'),
    url(r'^500$', views.page_error),
    url(r'^test$', views.test, name='test'),
]

django_blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'

# ... the rest of your URLconf goes here ...

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('auth.urls')),
    url(r'^web-spider/', include('webSpider.urls')),
    url(r'', include('blog.urls')),
]
urlpatterns += staticfiles_urlpatterns()

webSpider/urls.py
# -*- coding: utf-8 -*-
"""web spider URL Configuration
"""
from django.conf.urls import url

from . import views

app_name = 'web_spider'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^top250/$', views.top250, name='top250'),
    url(r'^nba/$', views.nba, name='nba'),
    url(r'^zhihu/$', views.zhihu, name='zhihu'),
]

blog/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.core.validators import RegexValidator


# 注册
class RegisterForm(forms.Form):
    error_msg = {
        'username': {'required': '用户名不能为空', 'max_length': '最大20', 'min_length': '用户名长度至少6'},
        'password': {'required': '用户名密码不能为空', 'max_length': '最大20', 'min_length': '密码长度至少6'},
    }
    username = forms.CharField(label='用户名', min_length=6, max_length=20, required=True,
                               error_messages=error_msg['username'])
    password = forms.CharField(label='密码', min_length=6, max_length=20, required=True,
                               validators=[
                                   RegexValidator(r'((?=.*\d))^.{6,20}$', '密码必须包含数字'),
                                   RegexValidator(r'((?=.*[a-zA-Z]))^.{6,20}$', '密码必须包含字母'),
                                   RegexValidator(r'((?=.*[^a-zA-Z0-9]))^.{6,20}$', '密码必须包含特殊字符'),
                                   RegexValidator(r'^.(\S){6,20}$', '密码不能包含空白字符'),
                               ],  # 用于对密码的正则验证
                               error_messages=error_msg['password'], widget=forms.PasswordInput)
    password_again = forms.CharField(label='确认密码', min_length=6, max_length=20, required=True,
                                     error_messages={'required': '密码不能为空!'}, widget=forms.PasswordInput)

    email = forms.EmailField(
        label='邮箱',
        required=True,
        min_length=6,
        max_length=30,
        error_messages={'required': '邮箱不能为空',
                        'invalid': '请输入正确的邮箱格式'},
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        users = User.objects.filter(username=username)
        print(username)
        if users:
            raise forms.ValidationError("用户名已经存在")
        return username

    def clean_email(self):
        # 对email的扩展验证，查找用户是否已经存在
        email = self.cleaned_data.get('email')
        email_count = User.objects.filter(email=email).count()  # 从数据库中查找是否用户已经存在
        if email_count:
            raise forms.ValidationError('该邮箱已经注册！')
        return email

    def clean__password_again(self):  # 查看两次密码是否一致
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password_again')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError('两次密码不匹配！')


# 登录
class LoginForm(forms.Form):
    error_msg = {
        'username': {'required': '用户名不能为空', 'max_length': '最大20', 'min_length': '至少6'},
        'password': {'required': '用户名密码不能为空', 'max_length': '最大20', 'min_length': '至少6'},
    }
    username = forms.CharField(label='用户名', min_length=6, max_length=20, required=True,
                               error_messages=error_msg['username'])
    password = forms.CharField(label='密码', min_length=6, max_length=20, required=True,
                               error_messages=error_msg['password'], widget=forms.PasswordInput)

templates/footer.html
<div class="footer text-center foot-nav">
    © 2018 wangjiale的个人博客 <a href="/" target="_blank">by Jiale Wang</a>
</div>

templates/nav.html
{% load staticfiles %}
<nav class="navba navbar-default my-head" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <a class="nav-bar-logo" title="首页" href="/">
            <img id="index-logo" src="{% static 'img/logo3.png' %}" alt="Logo" width="50px" height="50px"/>
        </a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                data-target="#navbar-collapse-1" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <div class="col-md-11">
            <div class="col-md-5">
                <ul class="nav navbar-nav">
                    <li class="navbar-form navbar-left">
                        <form action="{% url 'blog:search' %}" onsubmit="return checkSearchTitle()" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <input id="search-title" name="title" type="text" minlength="2" maxlength="10"
                                       class="form-control"
                                       placeholder="搜索博文">
                            </div>
                            <button type="submit" class="btn btn-default">搜索</button>
                        </form>
                    </li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">关于</a></li>
                    <li><a href="#">分类</a></li>
                    <li class="dropdown" style="width: 110px">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="width: 110px">
                            我的爬虫
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu" style="width: 100%; padding: 0; margin: 0;">
                            <li><a href="{% url 'web_spider:nba' %}">查看nba今日得分</a></li>
                            <li><a href="{% url 'web_spider:top250' %}">爬取豆瓣top250</a></li>
                            <li><a href="{% url 'blog:404' %}">404</a></li>
                        </ul>
                    </li>
                    {% if not user.is_authenticated %}
                        <li><a href="{% url 'auth:login' %}">登录</a></li>
                        <li><a href="{% url 'auth:register' %}">注册</a></li>
                    {% else %}
                        <li><a href="javascript:">welcome, {{ user.username }}</a></li>
                        <li><a href="{% url 'auth:logout' %}">退出</a></li>
                    {% endif %}
                </ul>
            </div>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

<script>
    function checkSearchTitle() {
        if ($('#search-title').val() == "") {
            alert("请输入搜索的标题");
            return false;
        }
    }
</script>

templates/register.html
{% extends 'base.html' %}

{% block title %} 佳乐博客 注册 {% endblock %}

{% block body %}
    <div class="col-md-8">
        <div class="register">
            <div style="font-size: 25px; font-weight: bold;text-align: center;">
                用户注册
            </div>
            <form role="form" action="{% url 'auth:register' %}" method="POST" novalidate="NOVALIDATE">{% csrf_token %}
                <div class="form-group">
                    <label for="username">{{ form.username.label }}</label>
                    {{ form.username }} <span style="color: red">{{ form.username.errors }}</span>

                </div>
                <div class="form-group">
                    <label for="email">{{ form.email.label }}</label>
                    {{ form.email }}<span style="color: red">{{ form.email.errors }}</span>
                </div>
                <div class="form-group">
                    <label for="password">{{ form.password.label }}</label>
                    {{ form.password }}<span style="color: red">{{ form.password.errors.0 }}</span>
                </div>
                <div class="form-group">
                    <label for="confirm_password">{{ form.password_again.label }}</label>
                    {{ form.password_again }}
                    <span style="color: red">
                {{ form.password_again.errors.0 }}</span>
                </div>

                <input type="submit" class="btn btn-default" value="注册"/>
                <!-- <span>已有账号？<a href="/login/">直接登录</a></span> -->
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            for (let i = 1; i < 5; i++) {
                let base_nav_bottom_li_id = "base-nav-bottom-li-" + i;
                $('#' + base_nav_bottom_li_id).removeClass('active');// remove class
            }
            $("#base-nav-bottom-li-4").addClass('active');
        });
    </script>
{% endblock %}

templates/register2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1"/>
    <title>注册 - 佳乐的博客</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/jquery.2.1.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>
<body id="loginBody">
<div class="main" id="loginMain">
    <h2 class="title"><span id="title_login"
                            onclick="javascript:window.location.href=href='{% url 'auth:login' %}'">登录</span> · <span
            id="title_sign_up">注册</span>
    </h2>
    <div class="js-sign-in-container" style="margin-top: 30px;">
        <form>s
            <div class="form-group">
                <i class="glyphicon glyphicon-user"></i>
                <input type="text" name="username" maxlength="20" minlength="6" required id="id_username"
                       placeholder="用户名" onkeyup="check_user_name()"/>
            </div>
            <div class="form-group">
                <i class="glyphicon glyphicon-envelope"></i>
                <input type="email" name="email" maxlength="25" minlength="6" required id="id_email"
                       placeholder="邮箱" onkeyup="checkEmail()"/>
            </div>
            <div class="form-group">
                <i class="glyphicon glyphicon-lock"></i>
                <input type="password" name="password" maxlength="20" minlength="6" required id="id_password"
                       placeholder="密码"/>
            </div>
            <div class="form-group">
                <i class="glyphicon glyphicon-lock"></i>
                <input type="password" name="password_again" maxlength="20" minlength="6" required
                       id="id_password_again"
                       placeholder="确认密码"/>
            </div>
            <div class="form-group">
                <i class="glyphicon glyphicon-check"></i>
                <input type="text" id="vcode" name="vcode" maxlength="4" placeholder="验证码"/>
                <div style="position: absolute; top: 10px; right: 10px; display: flex; flex-direction: column;">
                    <span style="cursor: pointer" onclick="refreshVcode()" id="imgVcode"><img
                            src="{% url 'auth:verify_code' 1 %}"/></span>
                </div>
            </div>
            <input name="url_before" type="hidden" value="{{ url_before }}" class="form-group"/>
            {% csrf_token %}
            <div id="formErrors">
                <span>{{ form.username.errors }}</span>
                <span>{{ form.email.errors }}</span>
                <span>{{ form.password.errors.0 }}</span>
                <span>{{ form.password_again.errors.0 }}</span>
            </div>
            <div class="form-group">
                <span id="authErrorMsg" style="color: red; font-size: small;">
                </span>
                <input type="button" id="btnAuthSignUp" value="注册"/>
            </div>
            <!-- <span>已有账号？<a href="/login/">直接登录</a></span> -->
        </form>
        <div class="more-sign" style="margin-bottom: 30px;">
            <h4 class="title">社交帐号登录(建设中)</h4>
            <ul style="list-style:none; margin: 0; padding: 0; display: flex; flex-direction: row; justify-content: space-around;">
                <li><a id="weixin" class="weixin" target="_blank" href="javascript:0"><img
                        src="{% static 'img/social/webicon-wechat-m.png' %}"/></a></li>
                <li><a id="weibo" class="weibo" target="_blank" href="javascript:0"><img
                        src="{% static 'img/social/webicon-weibo-m.png' %}"/></a></li>
                <li><a id="github" class="github" target="_blank" href="javascript:0"><img
                        src="{% static 'img/social/webicon-github-m.png' %}"/></a></li>
                <li><a id="twitter" class="twitter" target="_blank" href="javascript:0"><img
                        src="{% static 'img/social/webicon-twitter-m.png' %}"/></a></li>
                <li><a id="linkedin" class="linkedin" target="_blank" href="javascript:0"><img
                        src="{% static 'img/social/webicon-linkedin-m.png' %}"/></a></li>
            </ul>

            <div class="weibo-geetest-captcha"></div>
        </div>
    </div>
</div>
</div>
<!-- check username-->
<script>
    let username_flag = 0;
    function check_user_name() {
        console.log(111);
        let username = $("input[name='username']").val();
        var str = "";
        if ("" == username) {
            str = "用户名为空";
        }
        else if ((username.length < 5) || (username.length > 20)) {
            str = "用户名必须为5 ~ 20位";
        }
        else if (check_other_char(username)) {
            str = "只能包含字母、数字和下划线";
        }
        else {
            document.getElementById('authErrorMsg').innerText = "";
            username_flag = 1;
        }
        document.getElementById('authErrorMsg').innerText = str;
    }

    // 验证用户名是否含有特殊字符
    function check_other_char(str) {
        console.log(222);
        var arr = ["&", "\\", "/", "*", ">", "<", "@", "!"];
        for (var i = 0; i < arr.length; i++) {
            for (var j = 0; j < str.length; j++) {
                if (arr[i] == str.charAt(j)) {
                    return true;
                }
            }
        }
        return false;
    }
</script>
<!-- check email-->
<script>
    function checkEmail() {
        console.log(333);
        let email = $("input[name='email']").val();
        let myReg = /^[a-zA-Z0-9_-]+@([a-zA-Z0-9]+\.)+(com|cn|net|org)$/;

        if (myReg.test(email)) {
            document.getElementById('authErrorMsg').innerText = "";
            document.getElementById('btnAuthSignUp').disabled = false;
            return true;
        } else {
            document.getElementById('authErrorMsg').innerText = "邮箱格式不对!";
            document.getElementById('btnAuthSignUp').disabled = true;
            return false;
        }
    };
</script>
<!-- submit button -->
<script>
    $(function () {
        $('#btnAuthSignUp').click(function () {
            console.log(1);
            const email = $("input[name='email']").val();
            const csrf = $("input[name='csrfmiddlewaretoken']").val();
            console.log("csrf is" + csrf);
            const vcode = $('#vcode').val();
            const username = $("input[name='username']").val();
            const password = $("input[name='password']").val();
            const password_again = $("input[name='password_again']").val();
            const url_before = $("input[name='url_before']").val();
            $('#vcode').val("");
            //发起ajax请求，注意csrf攻击
            console.log(1);
            $.post("{% url 'auth:sign_up_ajax_check' %}", {
                'csrfmiddlewaretoken': csrf,
                'username': username,
                'email': email,
                'password': password,
                'password_again':password_again,
                'vcode': vcode,
                'url_before': url_before,
            }, function (data) {
                console.log("data is ");
                console.log(data);
                //获取返回的数据并进行操作
                if (data.msg === 'ok') {
                    //登录成功
                    console.log(data.url);
                    location.href = data.url //跳转到成功页面
                } else {
                    //错误
                    console.log(data.error);
                    document.getElementById('authErrorMsg').innerText =(data.error[Object.keys(data.error)[0]]);
                    refreshVcode();
                }
            });
        });
    });

    function refreshVcode() {
        const temp_url = "{% url 'auth:verify_code' 1 %}" + Math.ceil(Math.random() * 10).toString();
        const temp_html = "<img src=" + '"' + temp_url + '"' + "/>";
        $('#imgVcode').html(temp_html);
    }
</script>
<!-- on load-->
<script>
    $(document).ready(function () {
        for (let i = 1; i < 5; i++) {
            let base_nav_bottom_li_id = "base-nav-bottom-li-" + i;
            $('#' + base_nav_bottom_li_id).removeClass('active');// remove class
        }
        $("#base-nav-bottom-li-4").addClass('active');
        $("#title_sign_up").addClass('active');
    });
</script>
<!-- onload xs css-->
<script>
    function load_background() {
        temp_url = "url('" + {% static ''%} +'img/bg_img/bg6.jpg' + "')";
        $("#loginBody").css("background-image", temp_url);
    }

    // 根据屏幕调整大框架的css
    function onload_login() {
        load_background();
        //判断是否宽屏
        let winWide = document.body.clientWidth;
        if (winWide <= 600) {
            $("#loginBody").css("background", "");
            $("#loginBody").css("background-color", '#454545');
            $("#loginMain").css("background-color", '#454545');
            $("#loginMain").css('width', '100%');
            $(".js-sign-in-container").css('width', '100%');
        }
    };
    window.onload = onload_login();
</script>
<style>
    .main {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 400px;
        transform: translate(-50%, -50%);
        text-align: center;
        padding: 0;
        background: rgba(255, 255, 255, 0.2);
        border-radius: 4px;
        box-shadow: 0 0 8px rgba(0, 0, 0, .1);
        display: inline-block;
    }

    .main .title {
        margin: 35px 0 20px 0;
        color: #eeeeee;
    }

    .main .title span {
        margin: 0 30px;
    }

    .main .title .active, .main .title span:hover {
        color: #5bc0de;
        border-bottom: 5px solid;
    }

    .js-sign-in-container {
        width: 300px;
        display: inline-block;
    }

    .js-sign-in-container .form-group {
        position: relative;
        font-size: 16px;
        margin: 0px 16px;

    }

    .js-sign-in-container .form-group i {
        z-index: 5;
        margin: 0;
        padding: 0;
        position: absolute;
        left: 12px;
        top: 18px;
    }

    .js-sign-in-container .form-group input {
        margin: 0;
        position: relative;
        border: 1px solid black;
        border-bottom: none;
        width: 100%;
        background-color: #f1f1f1;
        padding: 10px 0px 10px 40px;
        font-size: 18px;
    }

    .js-sign-in-container .form-group:first-of-type input {
        border-radius: 14px 14px 0 0;
    }

    .js-sign-in-container .form-group:nth-of-type(5) input {
        border-bottom: 1px solid black;
        border-radius: 0 0 14px 14px;
    }

    .js-sign-in-container input:focus {
        outline: none;
        border-color: #9ecaed;
        box-shadow: 0 0 10px #9e9aed;
    }

    .js-sign-in-container .form-group #authErrorMsg {
        z-index: 5;
        margin: 0;
        padding: 0;
        position: absolute;
        top: 55px;
        left: 50%;
        width: 150px;
        transform: translate(-50%, 0);
        text-align: center;
        color: red;
    }

    #btnAuthSignUp {
        margin-top: 25px;
        margin-bottom: 30px;
        width: 100%;
        padding: 12px 0;
        font-size: 18px;
        border: none;
        border-radius: 35px;
        color: #fff;
        background: #5bc0de;;
        cursor: pointer;
        outline: none;
        display: block;
        clear: both;
    }

    #btnAuthSignUp:hover {
        background: #0044BB;
    }

    #btnAuthSignUp[disabled] {
        background-color: #00a8c6;
        color: #bbbbbb;
        cursor: not-allowed;
    }

    .more-sign img {
        border-radius: 10px;
    }
</style>
</body>
</html>

templates/test.html
{% load staticfiles %}
<style type="text/css">
    .nav-logo {
        float: left;
        height: 40px;
        margin-top: 5px;
        overflow: hidden;
    }

    .nav-logo a {
        margin: 0;
        padding: 0;
    }
</style>
<!--导航-->
<nav class="navbar navbar-fixed-top navbar-default my-head">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#baseNavBar" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">首页</a>
        </div>
        <div class="collapse navbar-collapse" id="baseNavBar">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <form action="{% url 'blog:search' %}" onsubmit="return checkSearchTitle()" method="post" style="margin-top: 8px;">
                        {% csrf_token %}
                        <input id="search-title" name="title" type="text" minlength="2" maxlength="10"
                               class="form-control" style="width: 50%; display:inline;"
                               placeholder="搜索博文">
                        <button type="submit" class="btn btn-default">搜索</button>
                    </form>
                </li>
                <li><a href="#">关于</a></li>
                <li><a href="#">分类</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        我的爬虫
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" style="width: 100%; padding: 0; margin: 0;">
                        <li><a href="{% url 'web_spider:nba' %}">查看nba今日得分</a></li>
                        <li><a href="{% url 'web_spider:top250' %}">爬取豆瓣top250</a></li>
                        <li><a href="{% url 'blog:404' %}">404</a></li>
                    </ul>
                </li>
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'auth:login' %}">登录</a></li>
                    <li><a href="{% url 'auth:register' %}">注册</a></li>
                {% else %}
                    <li><a href="javascript:">welcome, {{ user.username }}</a></li>
                    <li><a href="{% url 'auth:logout' %}">退出</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<script type="text/javascript" src="{% static 'js/jquery.2.1.4.min.js' %}"></script>
<script>
    function checkSearchTitle() {
        if ($('#search-title').val() == "") {
            alert("请输入搜索的标题");
            return false;
        }
    }
</script>

templates/top_nav.html
{% load staticfiles %}
<style type="text/css">
    .nav-logo {
        float: left;
        height: 40px;
        margin-top: 5px;
        overflow: hidden;
    }

    .nav-logo a {
        margin: 0;
        padding: 0;
    }
</style>
<!--导航-->
<nav class="navbar navbar-fixed-top navbar-default my-head">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#baseNavBar" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">首页</a>
        </div>
        <div class="collapse navbar-collapse" id="baseNavBar">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <form action="{% url 'blog:search' %}" onsubmit="return checkSearchTitle()" method="post" style="margin-top: 8px;">
                        {% csrf_token %}
                        <input id="search-title" name="title" type="text" minlength="2" maxlength="10"
                               class="form-control" style="width: 50%; display:inline;"
                               placeholder="搜索博文">
                        <button type="submit" class="btn btn-default">搜索</button>
                    </form>
                </li>
                <li><a href="#">关于</a></li>
                <li><a href="#">分类</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        我的爬虫
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" style="width: 100%; padding: 0; margin: 0;">
                        <li><a href="{% url 'web_spider:nba' %}">查看nba今日得分</a></li>
                        <li><a href="{% url 'web_spider:top250' %}">爬取豆瓣top250</a></li>
                        <li><a href="{% url 'blog:404' %}">404</a></li>
                    </ul>
                </li>
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'auth:login' %}">登录</a></li>
                    <li><a href="{% url 'auth:register' %}">注册</a></li>
                {% else %}
                    <li><a href="javascript:">welcome, {{ user.username }}</a></li>
                    <li><a href="{% url 'auth:logout' %}">退出</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- end of top nav -->
<script type="text/javascript" src="{% static 'js/jquery.2.1.4.min.js' %}"></script>
<script>
    function checkSearchTitle() {
        if ($('#search-title').val() == "") {
            alert("请输入搜索的标题");
            return false;
        }
    }
</script>